const $=s=>document.querySelector(s);const KEY='tournament-manager-v1';
let state={name:'',poolCount:2,teams:[],pools:[],games:[],bracket:null};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)state=x}catch(e){}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function setupValues(){state.name=$('#tournamentName').value.trim();state.poolCount=+$('#poolCount').value;state.teams=[...new Set($('#teamsInput').value.split('\n').map(x=>x.trim()).filter(Boolean))]}
function drawPools(){setupValues();if(state.teams.length<2){$('#setupMsg').textContent='Add at least 2 teams.';return}if(state.poolCount>state.teams.length){$('#setupMsg').textContent='You cannot have more pools than teams.';return}$('#setupMsg').textContent='';state.pools=Array.from({length:state.poolCount},()=>[]);shuffle(state.teams).forEach((t,i)=>state.pools[i%state.poolCount].push(t));state.games=[];state.bracket=null;save();render()}
function renderPools(){const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';$('#pools').innerHTML=state.pools.map((p,i)=>`<div class="pool"><h3>Pool ${letters[i]||i+1}</h3><ol>${p.map(t=>`<li>${esc(t)}</li>`).join('')}</ol></div>`).join('')}
function makeGames(){state.games=[];state.pools.forEach((p,pi)=>{for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++)state.games.push({id:`p${pi}-${i}-${j}`,pool:pi,a:p[i],b:p[j],sa:'',sb:''})});state.bracket=null;save();render()}
function standingsForPool(pi){const teams=state.pools[pi]||[];const r=Object.fromEntries(teams.map(t=>[t,{team:t,w:0,l:0,t:0,rf:0,ra:0,gp:0}]));state.games.filter(g=>g.pool===pi&&g.sa!==''&&g.sb!=='').forEach(g=>{let a=r[g.a],b=r[g.b],sa=+g.sa,sb=+g.sb;a.gp++;b.gp++;a.rf+=sa;a.ra+=sb;b.rf+=sb;b.ra+=sa;if(sa>sb){a.w++;b.l++}else if(sb>sa){b.w++;a.l++}else{a.t++;b.t++}});return Object.values(r).map(x=>({...x,rd:x.rf-x.ra,pct:x.gp?(x.w+x.t*.5)/x.gp:0})).sort((a,b)=>b.pct-a.pct||b.rd-a.rd||b.rf-a.rf||a.team.localeCompare(b.team))}
function allStandings(){return state.pools.flatMap((_,i)=>standingsForPool(i).map(x=>({...x,pool:i}))).sort((a,b)=>b.pct-a.pct||b.rd-a.rd||b.rf-a.rf||a.team.localeCompare(b.team))}
function renderGames(){const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';$('#games').innerHTML=state.pools.map((p,pi)=>{let gs=state.games.filter(g=>g.pool===pi);return `<div class="gamePool"><h3>Pool ${letters[pi]} Games</h3>${gs.map(g=>`<div class="game"><span class="away">${esc(g.a)}</span><input class="score" inputmode="numeric" min="0" data-id="${g.id}" data-side="a" value="${g.sa}"><span class="versus">–</span><input class="score" inputmode="numeric" min="0" data-id="${g.id}" data-side="b" value="${g.sb}"><span>${esc(g.b)}</span></div>`).join('')}</div>`}).join('');document.querySelectorAll('.score').forEach(el=>el.addEventListener('input',e=>{let g=state.games.find(x=>x.id===e.target.dataset.id);let v=e.target.value.replace(/\D/g,'');e.target.value=v;g[e.target.dataset.side==='a'?'sa':'sb']=v;state.bracket=null;save();renderStandings()}))}
function standingsTable(rows,overall=false){return `<div class="tableScroll"><table><thead><tr><th>${overall?'Seed':'Team'}</th><th>GP</th><th>W</th><th>L</th><th>T</th><th>RF</th><th>RA</th><th>RD</th><th>Win%</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${overall?`<span class="seed">${i+1}</span>`:''}${esc(x.team)}</td><td>${x.gp}</td><td>${x.w}</td><td>${x.l}</td><td>${x.t}</td><td>${x.rf}</td><td>${x.ra}</td><td>${x.rd>0?'+':''}${x.rd}</td><td>${(x.pct*100).toFixed(0)}%</td></tr>`).join('')}</tbody></table></div>`}
function renderStandings(){if(!state.games.length)return;const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';$('#standings').innerHTML=state.pools.map((_,i)=>`<h3>Pool ${letters[i]}</h3>${standingsTable(standingsForPool(i))}`).join('')+`<h3>Overall Seeding</h3>${standingsTable(allStandings(),true)}`;$('#standingsSection').classList.remove('hidden')}
function nextPow2(n){let p=1;while(p<n)p*=2;return p}
function seedOrder(size){let arr=[1,2];while(arr.length<size){let n=arr.length*2,old=arr,neu=[];for(let x of old)neu.push(x,n+1-x);arr=neu}return arr}
function buildBracket(){let ranked=allStandings();if(ranked.length<2)return;let size=nextPow2(ranked.length),order=seedOrder(size),slots=order.map(seed=>ranked[seed-1]?.team||null);let rounds=[],matches=[];for(let i=0;i<size;i+=2)matches.push({a:slots[i],b:slots[i+1],sa:'',sb:'',winner:null});rounds.push(matches);for(let s=size/2;s>1;s/=2)rounds.push(Array.from({length:s/2},()=>({a:null,b:null,sa:'',sb:'',winner:null})));state.bracket={rounds};autoAdvance();save();renderBracket();$('#bracketSection').classList.remove('hidden');$('#bracketSection').scrollIntoView({behavior:'smooth'})}
function autoAdvance(){if(!state.bracket)return;for(let r=0;r<state.bracket.rounds.length;r++){state.bracket.rounds[r].forEach((m,i)=>{if(m.a&&!m.b)m.winner=m.a;else if(m.b&&!m.a)m.winner=m.b;if(m.winner&&r<state.bracket.rounds.length-1){let n=state.bracket.rounds[r+1][Math.floor(i/2)],side=i%2===0?'a':'b';if(n[side]!==m.winner){n[side]=m.winner;n.winner=null;n.sa='';n.sb=''}}})}}
function chooseWinner(r,i,team){let m=state.bracket.rounds[r][i];if(team!==m.a&&team!==m.b)return;m.winner=team;if(r<state.bracket.rounds.length-1){let n=state.bracket.rounds[r+1][Math.floor(i/2)],side=i%2===0?'a':'b';n[side]=team;n.winner=null;n.sa='';n.sb=''}autoAdvance();save();renderBracket()}
function renderBracket(){if(!state.bracket)return;const names=['Quarterfinals','Semifinals','Championship'];let rs=state.bracket.rounds;$('#bracket').innerHTML=`<div class="bracket">${rs.map((round,r)=>`<div class="round"><h3>${rs.length-r===1?'Championship':rs.length-r===2?'Semifinals':rs.length-r===3?'Quarterfinals':`Round ${r+1}`}</h3>${round.map((m,i)=>`<div class="match"><div class="teamRow ${m.winner===m.a&&m.a?'winner':''}"><button class="teamBtn" data-r="${r}" data-i="${i}" data-team="${esc(m.a||'')}" ${!m.a?'disabled':''}>${esc(m.a||'TBD')}</button></div><div class="teamRow ${m.winner===m.b&&m.b?'winner':''}"><button class="teamBtn" data-r="${r}" data-i="${i}" data-team="${esc(m.b||'')}" ${!m.b?'disabled':''}>${esc(m.b||'TBD')}</button></div>${m.a&&m.b?'<div class="matchActions">Tap a team to advance</div>':''}</div>`).join('')}</div>`).join('')}</div>`;document.querySelectorAll('.teamBtn:not(:disabled)').forEach(b=>b.addEventListener('click',()=>chooseWinner(+b.dataset.r,+b.dataset.i,b.dataset.team)));let final=rs.at(-1)[0];if(final?.winner){$('#champion').innerHTML=`🏆 Tournament Champion<strong>${esc(final.winner)}</strong>`;$('#champion').classList.remove('hidden')}else $('#champion').classList.add('hidden')}
function render(){ $('#tournamentName').value=state.name||'';$('#poolCount').value=state.poolCount||2;$('#teamsInput').value=(state.teams||[]).join('\n');let hasPools=state.pools?.length;$('#poolsSection').classList.toggle('hidden',!hasPools);if(hasPools)renderPools();let hasGames=state.games?.length;$('#gamesSection').classList.toggle('hidden',!hasGames);$('#standingsSection').classList.toggle('hidden',!hasGames);if(hasGames){renderGames();renderStandings()}$('#bracketSection').classList.toggle('hidden',!state.bracket);if(state.bracket)renderBracket()}
$('#drawBtn').addEventListener('click',drawPools);$('#redrawBtn').addEventListener('click',()=>{if(confirm('Re-draw the pools? Existing scores and bracket will be cleared.'))drawPools()});$('#gamesBtn').addEventListener('click',makeGames);$('#bracketBtn').addEventListener('click',buildBracket);$('#rebuildBracketBtn').addEventListener('click',buildBracket);$('#sampleBtn').addEventListener('click',()=>{$('#teamsInput').value=['GS Baseball','Dirtdogs','Bandits','Titans','Warriors','Braves','Bulldogs','Raptors'].join('\n')});$('#resetBtn').addEventListener('click',()=>{if(confirm('Delete this tournament and start over?')){localStorage.removeItem(KEY);state={name:'',poolCount:2,teams:[],pools:[],games:[],bracket:null};render()}});load();render();
