const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], KEY='tournament-manager-v2';
const fresh=()=>({name:'',poolCount:2,teams:[],pools:[],games:[],brackets:[],gamesPerTeam:2,fieldCount:2,startTime:'09:00',slotMinutes:75,ties:['pct','rd','rf','ra'],goldCount:4});let state=fresh(), drawTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function load(){try{state={...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){state=fresh()}}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function setupValues(){state.name=$('#tournamentName').value.trim();state.poolCount=+$('#poolCount').value;state.gamesPerTeam=+$('#gamesPerTeam').value;state.fieldCount=Math.max(1,+$('#fieldCount').value||1);state.startTime=$('#startTime').value||'09:00';state.slotMinutes=Math.max(15,+$('#slotMinutes').value||75);state.teams=[...new Set($('#teamsInput').value.split('\n').map(x=>x.trim()).filter(Boolean))]}
function randomPools(){state.pools=Array.from({length:state.poolCount},()=>[]);shuffle(state.teams).forEach((t,i)=>state.pools[i%state.poolCount].push(t));state.games=[];state.brackets=[]}
function drawPools(){setupValues();if(state.teams.length<2)return msg('Add at least 2 teams.');if(state.poolCount>state.teams.length)return msg('You cannot have more pools than teams.');msg('');randomPools();save();animateDraw()}
function msg(x){$('#setupMsg').textContent=x}
function animateDraw(){clearInterval(drawTimer);$('#drawStage').classList.remove('hidden');$('#poolsSection').classList.add('hidden');let target=state.pools.map(x=>[...x]), flat=[];target.forEach((p,pi)=>p.forEach(t=>flat.push({t,pi})));flat=shuffle(flat);let shown=target.map(()=>[]),idx=0;function paint(){const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ';$('#drawPools').innerHTML=shown.map((p,i)=>`<div class="pool"><h3>Pool ${L[i]}</h3><ol>${p.map(t=>`<li>${esc(t)}</li>`).join('')}</ol></div>`).join('')}function step(){if(idx>=flat.length){clearInterval(drawTimer);$('#drawTeam').textContent='Pools are set!';setTimeout(()=>{$('#drawStage').classList.add('hidden');$('#poolsSection').classList.remove('hidden');renderPools()},500);return}let x=flat[idx++];$('#drawTeam').textContent=x.t;shown[x.pi].push(x.t);paint()}paint();step();drawTimer=setInterval(step,550);$('#skipDrawBtn').onclick=()=>{clearInterval(drawTimer);$('#drawStage').classList.add('hidden');$('#poolsSection').classList.remove('hidden');renderPools()}}
function renderPools(){const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ';$('#pools').innerHTML=state.pools.map((p,i)=>`<div class="pool"><h3>Pool ${L[i]}</h3><div class="poolTeams">${p.map(t=>`<div class="poolTeam"><span>${esc(t)}</span><select class="moveTeam" data-team="${esc(t)}" aria-label="Move ${esc(t)}"><option value="">Move…</option>${state.pools.map((_,j)=>j===i?'':`<option value="${j}">Pool ${L[j]}</option>`).join('')}</select></div>`).join('')}</div></div>`).join('');$$('.moveTeam').forEach(s=>s.addEventListener('change',()=>{if(s.value==='')return;let from=state.pools.findIndex(p=>p.includes(s.dataset.team));state.pools[from]=state.pools[from].filter(t=>t!==s.dataset.team);state.pools[+s.value].push(s.dataset.team);state.games=[];state.brackets=[];save();render()}))}
function roundRobinPairs(p){let a=[...p];if(a.length%2)a.push(null);let out=[];for(let r=0;r<a.length-1;r++){for(let i=0;i<a.length/2;i++){let x=a[i],y=a[a.length-1-i];if(x&&y)out.push([x,y])}a=[a[0],a[a.length-1],...a.slice(1,-1)]}return out}
function makeGames(){state.games=[];let globalSlot=0;state.pools.forEach((p,pi)=>{let pairs=roundRobinPairs(p), limit=state.gamesPerTeam;if(limit>0){let counts=Object.fromEntries(p.map(t=>[t,0]));pairs=pairs.filter(([a,b])=>{if(counts[a]>=limit||counts[b]>=limit)return false;counts[a]++;counts[b]++;return true})}pairs.forEach(([a,b],k)=>{let slot=Math.floor(globalSlot/state.fieldCount),field=globalSlot%state.fieldCount+1;state.games.push({id:`${pi}-${k}-${Date.now()}`,pool:pi,a,b,sa:'',sb:'',field,time:addMins(state.startTime,slot*state.slotMinutes)});globalSlot++})});state.brackets=[];save();render()}
function addMins(t,m){let [h,n]=t.split(':').map(Number),z=h*60+n+m;return `${String(Math.floor(z/60)%24).padStart(2,'0')}:${String(z%60).padStart(2,'0')}`}
function fmtTime(t){let [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function rows(pi){
  const ts=state.pools[pi]||[];
  const r=Object.fromEntries(ts.map(t=>[t,{team:t,w:0,l:0,t:0,rf:0,ra:0,gp:0}]));
  state.games.filter(g=>g.pool===pi&&g.sa!==''&&g.sb!=='').forEach(g=>{
    const a=r[g.a],b=r[g.b],sa=+g.sa,sb=+g.sb;
    a.gp++; b.gp++; a.rf+=sa; a.ra+=sb; b.rf+=sb; b.ra+=sa;
    if(sa>sb){a.w++;b.l++} else if(sb>sa){b.w++;a.l++} else {a.t++;b.t++}
  });
  const result=Object.values(r).map(x=>({...x,rd:x.rf-x.ra,pct:x.gp?(x.w+x.t*.5)/x.gp:0}));
  return sortRows(result);
}
function sortRows(r){return r.sort((a,b)=>{for(let k of state.ties){let d=k==='ra'?a[k]-b[k]:b[k]-a[k];if(d)return d}return a.team.localeCompare(b.team)})} function allRows(){return sortRows(state.pools.flatMap((_,i)=>rows(i).map(x=>({...x,pool:i}))))}
function renderGames(){const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ';$('#games').innerHTML=state.pools.map((_,pi)=>`<div class="gamePool"><h3>Pool ${L[pi]}</h3>${state.games.filter(g=>g.pool===pi).map(g=>`<div class="game gameAdvanced"><div class="gameMeta"><input type="time" class="gameTime" data-id="${g.id}" value="${g.time}"><label>Field <input type="number" class="gameField" data-id="${g.id}" min="1" max="99" value="${g.field}"></label></div><div class="scoreLine"><span>${esc(g.a)}</span><input class="score" inputmode="numeric" data-id="${g.id}" data-side="a" value="${g.sa}"><b>–</b><input class="score" inputmode="numeric" data-id="${g.id}" data-side="b" value="${g.sb}"><span>${esc(g.b)}</span></div></div>`).join('')}</div>`).join('');$$('.score').forEach(el=>el.addEventListener('input',e=>{let g=state.games.find(x=>x.id===e.target.dataset.id),v=e.target.value.replace(/\D/g,'');e.target.value=v;g[e.target.dataset.side==='a'?'sa':'sb']=v;state.brackets=[];save();renderStandings()}));$$('.gameTime').forEach(e=>e.onchange=()=>{state.games.find(g=>g.id===e.dataset.id).time=e.value;save()});$$('.gameField').forEach(e=>e.onchange=()=>{state.games.find(g=>g.id===e.dataset.id).field=Math.max(1,+e.value||1);save()})}
function table(r,overall=false){return `<div class="tableScroll"><table><thead><tr><th>${overall?'Seed / Team':'Team'}</th><th>GP</th><th>W</th><th>L</th><th>T</th><th>RF</th><th>RA</th><th>RD</th><th>Win%</th></tr></thead><tbody>${r.map((x,i)=>`<tr><td>${overall?`<span class="seed">${i+1}</span>`:''}${esc(x.team)}</td><td>${x.gp}</td><td>${x.w}</td><td>${x.l}</td><td>${x.t}</td><td>${x.rf}</td><td>${x.ra}</td><td>${x.rd>0?'+':''}${x.rd}</td><td>${(x.pct*100).toFixed(0)}%</td></tr>`).join('')}</tbody></table></div>`}
const tieNames={pct:'Win %',rd:'Run Differential',rf:'Runs Scored',ra:'Runs Allowed'};
function renderTies(){ $('#tieBreakers').innerHTML=state.ties.map((k,i)=>`<span class="tieChip">${i+1}. ${tieNames[k]} <button data-i="${i}" data-d="-1" ${i===0?'disabled':''}>↑</button><button data-i="${i}" data-d="1" ${i===state.ties.length-1?'disabled':''}>↓</button></span>`).join('');$$('.tieChip button').forEach(b=>b.onclick=()=>{let i=+b.dataset.i,j=i+(+b.dataset.d);[state.ties[i],state.ties[j]]=[state.ties[j],state.ties[i]];save();renderStandings()})}
function renderStandings(){if(!state.games.length)return;const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ';renderTies();$('#standings').innerHTML=state.pools.map((_,i)=>`<h3>Pool ${L[i]}</h3>${table(rows(i))}`).join('')+`<h3>Overall Seeding</h3>${table(allRows(),true)}`;$('#standingsSection').classList.remove('hidden')}
function nextPow2(n){let p=1;while(p<n)p*=2;return p} function seedOrder(size){if(size===1)return[1];let a=[1,2];while(a.length<size){let n=a.length*2,o=a,z=[];o.forEach(x=>z.push(x,n+1-x));a=z}return a}
function makeBracket(name,teams){if(teams.length<2)return null;let size=nextPow2(teams.length),slots=seedOrder(size).map(s=>teams[s-1]||null),rounds=[];rounds.push(Array.from({length:size/2},(_,i)=>({a:slots[i*2],b:slots[i*2+1],winner:null})));for(let n=size/4;n>=1;n/=2)rounds.push(Array.from({length:n},()=>({a:null,b:null,winner:null})));return{name,rounds}}
function buildBrackets(){state.goldCount=Math.max(2,Math.min(allRows().length,+$('#goldCount').value||4));let ranked=allRows().map(x=>x.team),gold=ranked.slice(0,state.goldCount);state.brackets=[makeBracket('Gold',gold)];state.brackets.forEach(autoAdvance);save();render();$('#bracketSection').scrollIntoView({behavior:'smooth'})}
function autoAdvance(br){for(let r=0;r<br.rounds.length;r++)br.rounds[r].forEach((m,i)=>{if(m.a&&!m.b)m.winner=m.a;else if(m.b&&!m.a)m.winner=m.b;if(m.winner&&r<br.rounds.length-1){let n=br.rounds[r+1][Math.floor(i/2)],side=i%2?'b':'a';n[side]=m.winner}})}
function advance(bi,r,i,team){let br=state.brackets[bi],m=br.rounds[r][i];if(![m.a,m.b].includes(team))return;m.winner=team;if(r<br.rounds.length-1){let n=br.rounds[r+1][Math.floor(i/2)],side=i%2?'b':'a';n[side]=team;n.winner=null}autoAdvance(br);save();renderBrackets()}
function renderBrackets(){let html='';state.brackets.forEach((br,bi)=>{html+=`<div class="bracketBlock"><h2>${br.name} Bracket</h2><div class="bracket">${br.rounds.map((round,r)=>`<div class="round"><h3>${r===br.rounds.length-1?'Championship':br.rounds.length-r===2?'Semifinals':br.rounds.length-r===3?'Quarterfinals':`Round ${r+1}`}</h3>${round.map((m,i)=>`<div class="match">${['a','b'].map(s=>`<div class="teamRow ${m.winner===m[s]&&m[s]?'winner':''}"><button class="teamBtn" data-bi="${bi}" data-r="${r}" data-i="${i}" data-team="${esc(m[s]||'')}" ${!m[s]?'disabled':''}>${esc(m[s]||'TBD')}</button></div>`).join('')}</div>`).join('')}</div>`).join('')}</div>`;let f=br.rounds.at(-1)[0];if(f?.winner)html+=`<div class="champion">🏆 ${br.name} Champion<strong>${esc(f.winner)}</strong></div>`;html+='</div>'});$('#brackets').innerHTML=html;$$('.teamBtn:not(:disabled)').forEach(b=>b.onclick=()=>advance(+b.dataset.bi,+b.dataset.r,+b.dataset.i,b.dataset.team))}
function render(){ $('#tournamentName').value=state.name;$('#poolCount').value=state.poolCount;$('#gamesPerTeam').value=state.gamesPerTeam;$('#fieldCount').value=state.fieldCount;$('#startTime').value=state.startTime;$('#slotMinutes').value=state.slotMinutes;$('#teamsInput').value=state.teams.join('\n');let hp=state.pools.length;$('#poolsSection').classList.toggle('hidden',!hp);if(hp)renderPools();let hg=state.games.length;$('#gamesSection').classList.toggle('hidden',!hg);$('#standingsSection').classList.toggle('hidden',!hg);if(hg){renderGames();renderStandings()}$('#goldCount').value=state.goldCount;$('#bracketSection').classList.toggle('hidden',!state.brackets.length);if(state.brackets.length)renderBrackets()}
for(let i=1;i<=8;i++)$('#poolCount').insertAdjacentHTML('beforeend',`<option ${i===2?'selected':''}>${i}</option>`);$('#drawBtn').onclick=drawPools;$('#redrawBtn').onclick=()=>{if(confirm('Re-draw pools? Existing scores and brackets will be cleared.')){setupValues();randomPools();save();animateDraw()}};$('#gamesBtn').onclick=makeGames;$('#bracketBtn').onclick=buildBrackets;$('#rebuildBracketBtn').onclick=buildBrackets;$('#sampleBtn').onclick=()=>{$('#teamsInput').value=['GS Baseball','Dirtdogs','Bandits','Titans','Warriors','Braves','Bulldogs','Raptors'].join('\n')};$('#resetBtn').onclick=()=>{if(confirm('Delete this tournament and start over?')){localStorage.removeItem(KEY);state=fresh();render()}};load();render();
